search:
  host: localhost

# Old values
# database:
#   host: localhost
#   user: fusionauth
#   password: password123
#   root:
#     user: postgres
#     password: password234

# New values
# database:
#   host: localhost
#   dbUser:
#     username: fusionauth
#     password: password
#   rootUser:
#     username: postgres
#     password: password

# Old values
# database:
#   host: localhost
#   user: fusionauth
#   existingSecret: fusionauth-db-creds
#   root:
#     user: postgres

# New values
database:
  host: localhost
  dbUser:
    username: fusionauth # name of the database user
    existingSecret:
      enabled: true
      name: fusionauth-db-creds # name of the k8s Secret
      passwordKey: password # name of the key that stores the password
  rootUser:
    username: postgres # name of the root user
    existingSecret:
      enabled: true
      name: fusionauth-root-creds # name of the k8s Secret
      passwordKey: password # name of the key that stores the root password
