{{- if .Values.kickstart.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "fusionauth.fullname" . }}-kickstart-config
  labels:
    {{- include "fusionauth.labels" . | nindent 4 }}
data:
  {{- if .Values.kickstart.data }}
  {{- range $key, $value := .Values.kickstart.data }}
  {{ $key }}: |
{{ $value | indent 4 }}
  {{- end -}}
{{- end -}}
{{- end -}}
