{{- if .Values.kickstart.enabled }}
{{- if not .Values.kickstart.data }}
{{- fail "kickstart.data must contain at least one file when kickstart.enabled is true" }}
{{- end }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "fusionauth.fullname" . }}-kickstart-config
  labels:
    {{- include "fusionauth.labels" . | nindent 4 }}
data:
  {{- range $key, $value := .Values.kickstart.data }}
  {{ $key }}: |
{{ $value | indent 4 }}
  {{- end -}}
{{- end -}}
