{{- $databasePasswordEnv := eq (include "fusionauth.environment.has" (dict "context" . "name" "DATABASE_PASSWORD")) "true" -}}
{{- $databaseRootUsernameEnv := eq (include "fusionauth.environment.has" (dict "context" . "name" "DATABASE_ROOT_USERNAME")) "true" -}}
{{- $databaseRootPasswordEnv := eq (include "fusionauth.environment.has" (dict "context" . "name" "DATABASE_ROOT_PASSWORD")) "true" -}}
{{- $databaseRootUserConfigured := or .Values.database.root.user $databaseRootUsernameEnv -}}
{{- if eq (include "fusionauth.database.generatedSecret.enabled" .) "true" -}}
{{- if and (not $databaseRootPasswordEnv) $databaseRootUserConfigured (not .Values.database.root.password) -}}
{{- fail "database.root.password is required when database.root.user is set and database.existingSecret.enabled is false" }}
{{- end -}}
apiVersion: v1
data:
{{- if not $databasePasswordEnv }}
  password: {{ required "A password for your database is required!" .Values.database.password | b64enc }}
{{- end }}
{{- if and $databaseRootUserConfigured (not $databaseRootPasswordEnv) }}
  rootpassword: {{ .Values.database.root.password | b64enc }}
{{- end }}
kind: Secret
metadata:
  labels:
    {{- include "fusionauth.labels" . | nindent 4 }}
  name: {{ include "fusionauth.database.secretName" . }}
type: Opaque
{{- end -}}
