{{- $fusionauthUserGeneratedSecretEnabled := eq (include "fusionauth.database.fusionauthUser.generatedSecret.enabled" .) "true" -}}
{{- $rootUserGeneratedSecretEnabled := eq (include "fusionauth.database.rootUser.generatedSecret.enabled" .) "true" -}}
{{- if $fusionauthUserGeneratedSecretEnabled -}}
{{- if not (include "fusionauth.database.fusionauthUser.password" .) -}}
{{- fail "database.fusionauthUser.password is required when database.fusionauthUser.existingSecret.enabled is false" }}
{{- end -}}
apiVersion: v1
data:
  password: {{ include "fusionauth.database.fusionauthUser.password" . | b64enc }}
kind: Secret
metadata:
  labels:
    {{- include "fusionauth.labels" . | nindent 4 }}
  name: {{ include "fusionauth.database.fusionauthUser.secretName" . }}
type: Opaque
{{- end }}
{{ if $rootUserGeneratedSecretEnabled }}
{{ if $fusionauthUserGeneratedSecretEnabled }}
---
{{ end }}
{{- if not (include "fusionauth.database.rootUser.password" .) -}}
{{- fail "database.rootUser.password is required when database.rootUser.username is set and database.rootUser.existingSecret.enabled is false" }}
{{- end -}}
apiVersion: v1
data:
  password: {{ include "fusionauth.database.rootUser.password" . | b64enc }}
kind: Secret
metadata:
  labels:
    {{- include "fusionauth.labels" . | nindent 4 }}
  name: {{ include "fusionauth.database.rootUser.secretName" . }}
type: Opaque
{{- end -}}
