{{- if eq .Values.database.existingSecret "" -}}
apiVersion: v1
data:
  password: {{ required "A password for your database is required!" ( include "fusionauth.tpl" (dict "value" .Values.database.password "context" $)) | b64enc }}
{{- if (include "fusionauth.tpl" (dict "value" .Values.database.root.password "context" $)) }}
  rootpassword: {{ (include "fusionauth.tpl" (dict "value" .Values.database.root.password "context" $)) | b64enc }}
{{- end }}
kind: Secret
metadata:
  labels:
    app.kubernetes.io/name: {{ include "fusionauth.name" . }}
    helm.sh/chart: {{ include "fusionauth.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  name: {{ include "fusionauth.database.secretName" . }}
type: Opaque
{{- end -}}
